### PR TITLE
Subject line for SendGrid Activity screen

### PR DESCRIPTION
**Pull request by foliovision**
Hello Callum,

as you might know the dedicated SMTP service SendGrid provides no details about what emails were sent on their Activity Screen (that's how the call the log screen).

We are contributing an improvement for your plugin which detects use of SendGrid and appends these email headers. I'm sure your SendGrid users (like we are) will be thrilled to see this new feature.

Thanks,
Martin

### CODE REVIEW

**Comment by foliovision** [comment]
Hello Callum,

could you please provide some details why you are not accepting our pull request?

Thanks,
Martin

**Comment by chmac** [comment]
The plugin maintainer has changed.

**Comment by foliovision** [comment]
Hi Callum,

Could you give us a reason why you would not like to provide full support for SendGrid even when it's handed to you on a silver platter?

A bit discouraging this approach to Open Source (improve people's code and they just close the issue).

Thanks.

Alec

**Comment by chmac** [comment]
I wouldn't have merged your PR anyway, even if I was still maintaining the plugin. It adds too much code that will only affect too few people.

**Comment by foliovision** [comment]
Hi Callum,

SendGrid (after Mandrill more or less left the market) is the giant in the SMTP space. This is not a lot of code and might be useful to other applications. So to get a working plugin we have to fork. This is so not cool Callum and unfortunately very symptomatic of a [rather shitty WordPress world](https://core.trac.wordpress.org/ticket/12423#comment:112) these days.

Thanks anyway, Alec

**Comment by chmac** [comment]
It appears to me that you're confusing open source with "public space". This plugin was mine and mine alone to maintain. It was 100% my decision what made sense for the plugin and what didn't. Feel free to fork it and implement your feature if you want to.

You submitted a PR, it was rejected.

**Pull request closed without merging**
